export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const CREATE_STREAM = 'CREATE_STREAM'
export const FETCH_STREAMS = 'FECH_STREAMS'
export const FETCH_STREAM = 'FECH_STREAM'
export const DELETE_STREAM = 'DELETE_STREAM'
export const EDIT_STREAM = 'EDIT_STREAM'
